services:
  - type: web
    name: whatsapp-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_URI_DEV
        sync: false
      - key: JWT_SECRET
        sync: false
      # Meta WhatsApp API credentials
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: META_VERIFY_TOKEN
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: META_WEBHOOK_URL
        sync: false
      # Relay system
      - key: RELAY_SECRET
        sync: false
      # Target URLs
      - key: LK_URL
        sync: false
      - key: DASH_URL
        sync: false
    healthCheckPath: /api/health 